### ISSUE TITLE
Values very inaccurate using 5v

### ISSUE THREAD

**Issue by pghpete** [adafruit/Adafruit_CircuitPython_HTS221#4]
I thought, perhaps, this sensor needed a few days to "settle" to get close to its suggested accuracy however that is not happening and the values are way off.

I am using a pi3b+ and the adafruit hts221 breakout board and 5v to power it. (using i2c).

I continue to get RH measurements 12-20% lower than expected and temperatures 13-25 degrees F higher than what I should be seeing.

I have half a dozen of these and will be replacing this one with another to see if it is this particular sensor or something else with my setup.

The only thing I did to the example code was add a line to convert C to F.

Here is the code for reference.

```
#!/usr/bin/python3    
import time
import board
import busio
import adafruit_hts221
     
i2c = busio.I2C(board.SCL, board.SDA)
hts = adafruit_hts221.HTS221(i2c)

# Celsius to Fahrenheit
temp_f = hts.temperature * 9/5.0 + 32
print('Relative Humidity: {0:0.2f} %% rH {1:0.2f} F'.format(hts.relative_humidity, temp_f))
print('Temperature: {0:0.2f} C'.format(hts.temperature))
```
I am using Raspbian 10 (buster), and I am using a 5v rail to power the breakout board.  Are there any other reports of this inaccuracy? Does this break out board behave better on 3.3v?

**Comment by ladyada** [comment]
yes please follow the wiring here https://learn.adafruit.com/adafruit-hts221-temperature-humidity-sensor/python-circuitpython#python-computer-wiring-3056860-3

**Comment by pghpete** [comment]
? This is wired up correctly and according to the breakout board learning pages, it can take 3.3 or 5v in. is this not correct?

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/86398387-85300880-bc73-11ea-8d4c-9649ec4ae462.png)


![image](https://user-images.githubusercontent.com/1214161/86398354-78abb000-bc73-11ea-8acd-725004f3a6a5.png)

**Comment by pghpete** [comment]
Ok thank you. That is very confusing as it implies you can use 5v or 3.3v in several places. I will put this on a 3.3v rail and see if my results are more accurate. Appreciate your help!! Stay Safe!

**Comment by pghpete** [comment]
I was mistaken. This was already on the 3.3v rail and these were the numbers I was getting.  I just switched it to 5v to see if that made a difference and it didn't. I will swap out the sensor now to see if it is just this particular sensor.

**Comment by pghpete** [comment]
Ok something else is the issue... This is a new sensor, on the 3.3v rail, with new wiring (4" vs 6'). So two different sensors on different wires hooked up separately are reporting the same very high temprature and very low RH.

This is a block from my house...
Indianola, PA Weather Conditions
88  Harmar PA WindStax Station

The sensor is in an acurite radiation shield so out of direct sunlight, properly vented etc and I am getting this from both sensors...
Relative Humidity: 23.86 %% rH 103.40 F
Temperature: 39.67 C

**Comment by pghpete** [comment]
I have tried mulitple sensors, with different wiring and have the same issue with them.  (on i2c). I am going to try them on a completely different pi.  I have half a dozen of these sensors now, some bought directly from adafruit and some from digikey and so far I cannot get these sensors anywhere close to accurate.  I will report back here with the results of these sensors on a completely different pi.

**Comment by pghpete** [comment]
I have tried mulitple sensors, with different wiring and have the same issue with them.  (on i2c). I am going to try them on a completely different pi.  I have half a dozen of these sensors now, some bought directly from adafruit and some from digikey and so far I cannot get these sensors anywhere close to accurate.  These sensors have been tried on a raspberry pi3b+ and a raspberry pi4.  Is there no other way to tune this code or get at least close to the advertised accuracy both on the adafruit site and the datasheet for the chip?

**Comment by tannewt** [comment]
@pghpete The math in the library looks right to me.

Please also do these prints:
```
print(hts.calibrated_value_1, hts.calib_temp_meas_1)
print(hts.calib_temp_value_0, hts.calib_temp_meas_0)
print(hts._raw_temperature, hts.temperature)
print(hts.calib_hum_value_1, hts.calib_hum_meas_1)
print(hts.calib_hum_value_0, hts.calib_hum_meas_0)
print(hts._raw_humidity, hts.relative_humidity)
```

This will print the calibration values and the current raw values.

Please also post a picture of your setup with the sensor connected to the Raspberry Pi. Thanks!

**Comment by pghpete** [comment]
Thanks for the reply @tannewt .  

Here is the output for the print statements. Today it appears the temperature is close to spec but the humidity is still off.

pi@garden:~/python $ ./hts221-test.py 
Relative Humidity: 40.10 %% rH 95.94 F
Temperature: 35.52 C
33 708
20 -4
846 35.51966292134831
70 -13131
30 -6
-3318 40.093714285714285

Actual Temp: Confirmed by local weather station and wunderground
93 degrees
Actual Humidity: Confirmed by local weather station and wunderground
47%

I actually took all readings I have and compared them to local weather station and wunderground and found, on average (with a reading every 5 minutes) the temperature is around 8% higher than actual. The humidity seams to be lower than expected by 9-15%.

I have attached two different setups with two different hts221 breakout boards but I am not sure you will be able to make out how the I2c connections are made due to my screw terminal hats and the general complexity of the main garden controller. However, I have attached photos anyway.

Large grey box is a rpi3b+, grey aluminium one with a screw terminal hat is a rpi4 8gb running the 64bit Raspbian OS (beta?).

First image shows the insides, on the upper left of the screw terminal (from the view in the pic) are the sda/sdl connections. Please note: I wired this and picked my own colors of wire for SDA/SDL lines before realizing adafruit has them different (for the stemma qt pigtails) so while the colors are different, SDA is connected to SDA and SDL is connected to SDL as expected.

Adafruit colors for stemma qt pigtail vs my colors for wiring...
    Black for GND
    Red for V+
    Blue for SDA (mine is YELLOW here)
    Yellow for SCL (mine is BLUE here)


![20200528_233421](https://user-images.githubusercontent.com/15705432/87076084-3fcd8700-c1ef-11ea-847f-a6de4d7bc371.jpg)

This is the enclosure with all sensors connected except the relay leads to the solenoid manifold (not pictured)
![20200529_144404](https://user-images.githubusercontent.com/15705432/87076101-45c36800-c1ef-11ea-81e7-79a447908f77.jpg)

You can see the white pole off to the left that holds the radiation shield which contains the sensor in this image.
![20200529_144417](https://user-images.githubusercontent.com/15705432/87076121-4956ef00-c1ef-11ea-82e3-6f8ea68c4026.jpg)

Here is a completely different sensor, with a stemma QT pigtail (colors match adafruts here) on a rpi4.  The sensor is barely visible between my fingers and the power cord.  It exhibits the same issue.
![20200708_190500](https://user-images.githubusercontent.com/15705432/87076139-4eb43980-c1ef-11ea-9331-ee43bb1b6be7.jpg)

**Comment by pghpete** [comment]
I don't know why this would be the case or even if its possible, but could these sensors need some time to come into spec?  Today (or at least at this moment) the one in the main box is an acceptable deviation in both humidity and temperature but for the last two weeks or more it was significantly off.

**Comment by pghpete** [comment]
I spoke too soon. Here is what is currently being reported by the sensor and what "actual" temps are being reported as...

/home/pi/python/hts221.py                                                garden: Thu Jul  9 14:54:10 2020

Relative Humidity: 38.10 % rH 100.31 F

Actual: 55 %RH  91F

**Comment by ladyada** [comment]
datasheet has this to say

```
The HLGA package is compliant with the ECOPACK® standard and it is qualified for
soldering heat resistance according to JEDEC J-STD-020. After soldering, the accuracy
specification of the sensor can be guaranteed after re-hydration of the sensor element in a
stabilized environment (25 °C / 55% rH) for 3 days or at 70% rH for 12 h. Otherwise the
sensor may read an offset that slowly disappears if exposed to ambient conditions.
```

wanna try that?

**Comment by pghpete** [comment]
Thanks for the response. I am not sure I'd be able to hit and hold both temperature and humidity values listed in the data sheet for that amountof time... however, I wonder if it just needs a stable humidity and temperature for X days.  With a dehumidifier in my underground basement it is a stable 41%RH and 64 degrees F. (I monitor this for lumber drying purposes lol) I'm going to put one down there and leave it for a while and see if that helps. I did take these directly from the bags they came in and immediately put them outside in appropriate enclosures. I will report back.

**Comment by ladyada** [comment]
i think it needs to 'rehumidity' - do you have a humidifier?

**Comment by pghpete** [comment]
I can get one. I also have a relay controllable power strip so I may be able to hack something together with fairly decent accuracy.

-------- Original Message --------

**Comment by pghpete** [comment]
I was able to keep the sensor at 77 degrees F +-2 degrees, and RH 70% +-2% for 14 hours.  (hopefully this rehydration procedure is suppose to be one while sensor an break out board is powered on?)  I have relocated it outside to again check to see if it is closer to other sensors and weather reports.  **Before:** +/- 12-20% RH, +/- 13-25F **After:** +/- 3% RH, +/- 2-5 degrees.  So it is much much better. I am not yet calling this a victory because I would like to see a few days/nights of different temperature ranges and compare their accuracy as well.  However, I am happy with this so far.  I may re-run the same hydration cycle again without the sensor powered, or do the 55% RH for 3 days cycle.

Once I have a verdict either way I will post here.  If I can reproduce this on a few more of the sensors after I have done it to this one I will share my procedures. (hopefully simplified, duplicated and tested on all 6 or so sensors I have at my disposal).

**Comment by siddacious** [comment]
@pghpete Thanks for the update. I'm glad to hear that things seem to be working better for you now and it the  rH measurement range you reported is within spec 
![image](https://user-images.githubusercontent.com/1183985/87366077-a541b080-c52c-11ea-9a42-5e09dd465ebb.png)
I look forward to hearing how the other sensors as well as your rehumidification procedures

**Comment by ladyada** [comment]
no, the sensor does not have to be operating during re-humidificaiton
@siddacious please add the above to the product guide, others may find it useful :)

**Comment by pghpete** [comment]
update: the rehydration may have worked...

For example, here is a weather station (noaa/wunderground) near me.
```
20200717 13:07:37 KPAPITTS370 Online
84.4F / 57 % RH
```

Here is what the rehydrated sensor is reading,
```
Fri 17 Jul 2020 01:14:48 PM EDT
Relative Humidity: 52.40 %% rH 87.95 F
Relative Humidity: 52.40 %% rH 31.08 C

```
However, I only poll these sensors once every 5 minutes... and when I did this manually, this is what I got. Both runs are seconds from each other...

```
:~/Scripts $ ./hts221.py 
Relative Humidity: 101.93 %% rH 73.54 F
Relative Humidity: 101.93 %% rH 23.08 C
:~/Scripts $ date ; ./hts221.py 
Fri 17 Jul 2020 01:14:48 PM EDT
Relative Humidity: 52.40 %% rH 87.95 F
Relative Humidity: 52.40 %% rH 31.08 C
```

I am wondering if I have to loop this, and read several times shipping those readings off to dev null before finally using one to send to io.adafruit.com.

**Comment by pghpete** [comment]
This process of rehydration is not regularly reproducible in a manor that makes these sensors at all functional to an acceptable degree of accuracy.  The second batch of rehydrated sensors still aren't functioning correctly...

~/Scripts $ ./hts221.py 
Relative Humidity: **127.36** %% rH 81.40 F
Relative Humidity: **127.36** %% rH 27.45 C

**Comment by pghpete** [comment]
Can we please reopen this issue? Not sure why it was closed.  This is still a problem and after purchasing a humidifier and controlling conditions to do this procedure, I have one barely acceptable sensor (in terms of accuracy) and 5 or 6 unusable due to them being so wildly out of spec.

**Comment by ladyada** [comment]
@siddacious please add some debug output support so we can see why the output is fluctuating

**Comment by siddacious** [comment]
@pghpete You can use this version I've modified to help debugging. You'll want to pass `debug=True` in the constructor, like
```hts = adafruit_hts221.HTS221(i2c, debug=True)```

**Comment by pghpete** [comment]
Thanks @siddacious ...

here is the output from one of my recently rehydrated sensors. (or after an attempt to rehydrate/calibrate it)

~/Scripts $ ./hts221-debug.py 
	DEBUG :: Humidity calibration constants:
	DEBUG :: measurement 0: 7
	DEBUG :: measurement 1: -13795
	DEBUG :: value 0: 30
	DEBUG :: value 1: 71
	DEBUG :: 
	DEBUG :: measurement delta: -13802
	DEBUG :: value delta: 41
	DEBUG :: 
	DEBUG :: value offset: 30
	DEBUG :: measurement offset: 7
	DEBUG :: 
	DEBUG :: correction scalar( -0.003) = value delta ( 41.000 ) / measurement delta ( -13802.000 )
	DEBUG :: 
	DEBUG :: raw humidity: -15060
	DEBUG :: zeroed humidity (-meas offset): -15067
	DEBUG :: 
	DEBUG :: real hum ( 74.758) = 
	DEBUG :: ( zeroed meas ( -15067.000 ) * calibration scalar( -0.003 ) + val offset ( 30.000 ))
	DEBUG :: 
Relative Humidity: 74.76 %% rH 72.89 F
	DEBUG :: raw humidity: -15060
	DEBUG :: zeroed humidity (-meas offset): -15067
	DEBUG :: 
	DEBUG :: real hum ( 74.758) = 
	DEBUG :: ( zeroed meas ( -15067.000 ) * calibration scalar( -0.003 ) + val offset ( 30.000 ))
	DEBUG :: 
Relative Humidity: 74.76 %% rH 22.71 C
